mongodb:
  image: mongo
  volumes:
     - ./mongodb:/data/db
  command: "mongod --smallfiles"

seyren:
  build: .
  ports:
    - "8080:8080"
  links:
    - mongodb
  env_file:
    - ./.env
  environment:
      MONGO_URL: mongodb://mongodb:27017/seyren
      SEYREN_URL: http://seyren:8080/seyren
      SEYREN_LOG_PATH: /var/log/seyren/
      # GRAPHITE_URL: http://graphite
      # GRAPHITE_USERNAME: guest
      # GRAPHITE_PASSWORD: guest
  volumes:
    - ./logs:/var/log/seyren



